name = "Lax57"
defaultTargets = ["Lax57"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax54"
git = "https://github.com/EdouardBonnet/EH-C5"
rev = "45be247a1207df525acc723286e7367f41d5801c"
subDir = "concepts"

[[lean_lib]]
name = "Lax57"
