name = "Lax57Proofs"
defaultTargets = ["Lax57Proofs"]

[leanOptions]
autoImplicit = false

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "db584cd6d46c92f209a44c0f1c829460d327499d"

[[require]]
name = "Lax57"
path = "../concepts"

[[require]]
name = "Lax54"
git = "https://github.com/EdouardBonnet/EH-C5"
rev = "63f5c9284f82bad4ea622526b93c4ddfb95fcae6"
subDir = "concepts"

[[require]]
name = "Lax54Proofs"
git = "https://github.com/EdouardBonnet/EH-C5"
rev = "63f5c9284f82bad4ea622526b93c4ddfb95fcae6"
subDir = "proofs"

[[lean_lib]]
name = "Lax57Proofs"
